name = "ad_lib"
authors = ["Jan Janiszewski"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"

[compat]
DrWatson = "2.12.4"
julia = "1.8.5"
